-- ============================================================
-- test-package-template.pck
-- Parameterized template for generating utPLSQL test packages
-- Used by taxone-test-data-engineer agent (Phase 8)
--
-- TEMPLATE VARIABLES (replace before compilation):
--   {{PACKAGE_NAME}}     — e.g., UT_IMP_SAFX3007_1066543
--   {{WI_ID}}            — e.g., 1066543
--   {{SAFX_TABLE}}       — e.g., SAFX3007
--   {{X_TABLE}}          — e.g., X3007_DOCTO_FISCAL_RT
--   {{COD_EMPRESA}}      — e.g., '076'
--   {{COD_ESTAB}}        — e.g., '01'
--   {{DATA_INI}}         — e.g., '01032026' (DDMMYYYY)
--   {{DATA_FIM}}         — e.g., '31032026' (DDMMYYYY)
--   {{GRUPO_ARQUIVO}}    — e.g., 5
--   {{NUMERO_ARQUIVO}}   — e.g., 1
--   {{SAFX_INSERT_BLOCK}} — Generated INSERT statements for SAFX data
--   {{PARENT_SETUP}}     — Parent table inserts (SAFX07 etc.) if needed
--   {{PARENT_CLEANUP}}   — Parent table cleanup if needed
--   {{TEST_PROCEDURES}}  — Generated ut_test_NNN procedures
--   {{TEST_DECLARATIONS}} — Procedure declarations for spec
--   {{DESCRIPTION}}      — Test suite description
-- ============================================================

CREATE OR REPLACE PACKAGE utpl010ac.{{PACKAGE_NAME}} IS

  -- WI {{WI_ID}} — {{DESCRIPTION}}
  -- Generated by taxone-test-data-engineer

  PROCEDURE ut_setup;
  PROCEDURE ut_teardown;

  {{TEST_DECLARATIONS}}

END {{PACKAGE_NAME}};
/

CREATE OR REPLACE PACKAGE BODY utpl010ac.{{PACKAGE_NAME}} IS

  -- Package-level variables for import lifecycle
  v_num_job      NUMBER;
  v_proc_ini     NUMBER;
  v_proc_fim     NUMBER;
  v_mens_err     NUMBER;

  -- ============================================================
  -- SETUP: Insert test data into SAFX staging tables
  -- ============================================================
  PROCEDURE ut_setup IS
  BEGIN
    {{PARENT_SETUP}}

    {{SAFX_INSERT_BLOCK}}

    COMMIT;
  END ut_setup;

  -- ============================================================
  -- TEARDOWN: Clean up all test data (FK-safe order)
  -- ============================================================
  PROCEDURE ut_teardown IS
  BEGIN
    -- 1. Clean child X table records
    -- DELETE {{X_TABLE}} WHERE ... (use NUM_DOCFIS pattern for traceability)

    {{PARENT_CLEANUP}}

    -- 2. Clean SAFX staging data
    DELETE {{SAFX_TABLE}}
     WHERE COD_EMPRESA = {{COD_EMPRESA}}
       AND COD_ESTAB   = {{COD_ESTAB}};

    -- 3. Clean import scheduling artifacts
    DELETE HIST_EXPORT
     WHERE GRUPO_ARQUIVO  = {{GRUPO_ARQUIVO}}
       AND NUMERO_ARQUIVO = {{NUMERO_ARQUIVO}};

    DELETE JOB_EXP_TAB
     WHERE GRUPO_ARQUIVO  = {{GRUPO_ARQUIVO}}
       AND NUMERO_ARQUIVO = {{NUMERO_ARQUIVO}};

    COMMIT;
  END ut_teardown;

  -- ============================================================
  -- TEST 001: Import via SAF_IMPORTA_TAB_SUITE lifecycle
  -- Validates that SAFX data is correctly imported to X table
  -- ============================================================
  PROCEDURE ut_test_001 IS
  BEGIN
    -- Step 1: Create import job
    MSAF_UTIL_INSERE.insere_job_importacao(
        p_tipo_job          => 'C',
        p_status_job        => 'P',
        p_data_abertura     => SYSDATE,
        p_data_encerramento => SYSDATE,
        p_ind_ato_cotepe    => 'N',
        p_num_job           => v_num_job);

    -- Step 2: Register SAFX table in job
    MSAF_UTIL_INSERE.insere_det_job_import(
        P_NUM_JOB          => v_num_job,
        P_GRUPO_ARQUIVO    => {{GRUPO_ARQUIVO}},
        P_NUMERO_ARQUIVO   => {{NUMERO_ARQUIVO}},
        P_COD_EMPRESA      => {{COD_EMPRESA}},
        P_COD_ESTAB        => {{COD_ESTAB}},
        P_DATA_INI         => TO_DATE('{{DATA_INI}}','DDMMYYYY'),
        P_DATA_FIM         => TO_DATE('{{DATA_FIM}}','DDMMYYYY'),
        P_PERC_ERRO        => 100,
        P_IND_ABORTA_JOB   => 'N',
        P_STATUS           => 'P',
        P_IND_DROP_TAB     => 'N',
        P_DAT_INI_EXEC     => SYSDATE,
        P_DAT_FIM_EXEC     => SYSDATE,
        P_IND_PERIODO      => 'N',
        P_IND_SOBREPOR_REG => 'S',
        P_IND_LOG_X2013    => 'N',
        P_IND_VALID_X2013  => 'N');

    -- Step 3: Execute import
    MSAF_UTIL.SAF_IMPORTA_TAB_SUITE(
        P_NUM_JOB  => v_num_job,
        P_USUARIO  => 'ut_{{WI_ID}}',
        P_PROC_INI => v_proc_ini,
        P_PROC_FIM => v_proc_fim,
        P_MENS_ERR => v_mens_err);

    -- Step 4: Validate — no import errors
    utAssert.eq(
        'Import should complete without errors',
        v_mens_err, 0);

    COMMIT;
  END ut_test_001;

  {{TEST_PROCEDURES}}

END {{PACKAGE_NAME}};
/

-- ============================================================
-- EXECUTION
-- ============================================================
-- To run all tests:
--   EXEC utPLSQL.test('{{PACKAGE_NAME}}');
--
-- To run a specific test:
--   EXEC utPLSQL.test('{{PACKAGE_NAME}}', '{{PACKAGE_NAME}}.UT_TEST_001');
-- ============================================================
